[instance: <*>] Attempting claim: memory <*> MB, disk <*> GB, vcpus <*> CPU
[instance: <*>] Claim successful
[instance: <*>] Creating image
[instance: <*>] Deleting instance files <*>
[instance: <*>] Deletion of <*> complete
[instance: <*>] disk limit not specified, defaulting to unlimited
[instance: <*>] During sync_power_state the instance has a pending task (spawning). Skip.
[instance: <*>] Instance destroyed successfully.
[instance: <*>] Instance spawned successfully.
[instance: <*>] memory limit: <*>.<*> MB, free: <*>.<*> MB
[instance: <*>] Terminating instance
[instance: <*>] Took <*>.<*> seconds to build instance.
[instance: <*>] Took <*>.<*> seconds to deallocate network for instance.
[instance: <*>] Took <*>.<*> seconds to destroy the instance on the hypervisor.
[instance: <*>] Took <*>.<*> seconds to spawn the instance on the hypervisor.
[instance: <*>] Total disk: <*> GB, used: <*>.<*> GB
[instance: <*>] Total memory: <*> MB, used: <*>.<*> MB
[instance: <*>] Total vcpu: <*> VCPU, used: <*>.<*> VCPU
[instance: <*>] vcpu limit not specified, defaulting to unlimited
[instance: <*>] VM Paused (Lifecycle Event)
[instance: <*>] VM Resumed (Lifecycle Event)
[instance: <*>] VM Started (Lifecycle Event)
[instance: <*>] VM Stopped (Lifecycle Event)
<*> "DELETE <*>" status: <*> len: <*> time: <*>.<*>
<*> "GET <*>" status: <*> len: <*> time: <*>.<*>
<*> "POST <*>" status: <*> len: <*> time: <*>.<*>
Active base files: <*>
Auditing locally available compute resources for node <*>
Base or swap file too young to remove: <*>
Compute_service record updated for <*>
Creating event network-vif-plugged:<*>-<*>-<*>-<*>-<*> for instance <*>
Final resource view: name=<*> phys_ram=<*> used_ram=<*> phys_disk=<*> used_disk=<*> total_vcpus=<*> used_vcpus=<*> pci_stats=[]
HTTP exception thrown: No instances found for any event
image <*> at (<*>): checking
image <*> at (<*>): in use: on this node <*> local, <*> on other nodes sharing this instance storage
Removable base files: <*>
Removing base or swap file: <*>
Running instance usage audit for host <*> from <*>-<*>-<*> <*>:<*>:<*> to <*>-<*>-<*> <*>:<*>:<*>. <*> instances.
Successfully synced instances from host '<*>'.
The instance sync for host '<*>' did not match. Re-created its InstanceList.
Total usable vcpus: <*>, total allocated vcpus: <*>
Unknown base file: <*>
While synchronizing instance power states, found <*> instances in the database and <*> instances on the hypervisor.
couldn't obtain the vcpu count from domain id: <*>, exception: Requested operation is not valid: cpu affinity is not supported
[instance: <*>] During sync_power_state the instance has a pending task (deleting). Skip.
oslo_service.periodic_task<*>
[instance: <*>] During sync_power_state the instance has a pending task (networking). Skip.
Error during <*>
Bad response code while validating token: <*>
Identity response: <*>
Unable to validate token: Failed to fetch token data from identity server
Deleted allocation for instance <*>
Neutron deleted interface <*>; detaching it from the instance and deleting it from the info cache
Periodic task is updating the host stats, it is trying to get disk info for <*>, but the backing disk storage was removed by a concurrent operation such as resize. Error: No disk at <*>: nova.exception.DiskNotFound: No disk at <*>
[instance: <*>] Traceback<*>
[instance: <*>]   File<*>
[instance: <*>]     <*>
[instance: <*>] 
Claim successful on node <*>
During sync_power_state the instance has a pending task (block_device_mapping). Skip.
During sync_power_state the instance has a pending task (powering-off). Skip.
During handling of the above exception, another exception occurred:
During the sync_power process the instance has moved from host <*> to host <*>
Instance is paused unexpectedly. Ignore.
During _sync_instance_power_state the DB power_state (<*>) does not match the vm_power_state from the hypervisor (<*>). Updating power_state in the DB to match the hypervisor.
Build of instance <*> aborted: Failed to allocate the network(s), not rescheduling.: nova.exception.BuildAbortException: Build of instance <*> aborted: Failed to allocate the network(s), not rescheduling.
<*> nova.exception.VirtualInterfaceCreateException: Virtual Interface creation failed<*>
oslo_db.sqlalchemy.update_match.NoRowsMatched: Zero rows matched for <*> attempts
Instance shutdown by itself. Calling the stop API. <*>
Received unexpected event <*> for instance with vm_state <*> and task_state <*>.
eventlet.timeout.Timeout: <*> seconds
Instance is already powered off in the hypervisor when stop is called.
<*> Conflict updating instance <*>. Expected: <*>
qemu-system-x86_64: terminating on signal <*> from pid <*> (/usr/sbin/libvirtd)
libvirt.libvirtError: Domain not found: no domain with matching uuid <*>
libvirt.libvirtError: internal error: process exited while connecting to monitor
libvirt.libvirtError: Requested operation is not valid: domain is not running
Ignoring supplied device name: <*>. Libvirt can't honour user-supplied dev names
Instance failed to spawn: nova.exception.FlavorDiskSmallerThanImage: Flavor's disk is too small for requested image. Flavor disk is <*> bytes, image is <*> bytes.
Build of instance <*> aborted: Flavor's disk is too small for requested image. Flavor disk is <*> bytes, image is <*> bytes.<*>
Get console output
<*> nova.scheduler.client.report [<*>] Unable to delete allocation for instance <*>: <*>
Booting with volume-backed-image <*> at <*>
Build of instance <*> aborted: Volume <*> did not finish being created even after we waited <*> seconds or <*> attempts. And its status is error.: <*>
Instance failed block device setup: nova.exception.VolumeNotCreated: Volume <*> did not finish being created even after we waited <*> seconds or <*> attempts. And its status is error.
error during stop() in sync_power_state.: nova.exception.InstanceInvalidState: Instance <*> in task_state powering-off. Cannot stop while the instance is in this state.
Instance <*> has allocations against this compute host but is not found in the database.
Instance <*> is not being actively managed by this compute host but has allocations referencing this compute host: <*>
<*> nova.exception.InstanceNotFound: Instance <*> could not be found.
Failed to delete allocations for consumer <*>. Error: <*>
ents: <*>
 <<*>>
